### PR TITLE
Add Puppet 8 support

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by ekohl** [comment]
And https://github.com/theforeman/puppet-puppetserver_foreman/pull/27 will also be needed on Ruby 3.

**Comment by ekohl** [comment]
And #28

**Review by ekohl — APPROVED** [review]
I took the liberty to rebase. :+1: If CI is green.

**Comment by bastelfreak** [comment]
@ekohl CI passed

**Pull request merged**
